"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Image from "next/image";
import PositionChart from "./position-chart";
import Faq from "./faq";
import SupportChat from "./support-chat";

type Config = { issuer: string; offerPriceNgn: string; minimumShares: number; quantityIncrement: number; opensOn: string; closesOn: string; lastVerified: string; snapshotRetrievedAt: string; version: string; sources: { label: string; url: string }[]; termsNote: string };
type Result = { shares: string; investmentCost: string; remainingCash: string | null; fees: string; totalCashRequired: string; estimatedPositionValue: string | null; potentialGainLoss: string | null; percentageReturn: string | null; breakEvenPrice: string; assumptions: { expectedSellingPrice: string | null }; ipoVersion: string };
const investmentPlatforms = [
  { label: "NGX Invest", url: "https://www.invest.ngxgroup.com/login" },
  { label: "Access Bank", url: "https://stocks.accessbankplc.com" },
  { label: "FirstBank", url: "https://firstdirect2.firstbanknigeria.com/dangote-ipo" },
  { label: "FCMB", url: "https://dipo.fcmb.com/" },
  { label: "Fidelity Bank", url: "https://www.fidelitybank.ng/dangote-ipo/" },
  { label: "Stanbic IBTC", url: "https://brokerage.stanbicibtc.com/offerportal/#/products/initial-public-offering" },
  { label: "InvestNaija", url: "https://investnaija.com/dangote-refinery-ipo/#subscribe" },
  { label: "Bamboo", url: "https://investbamboo.com/" },
  { label: "PiggyVest", url: "https://www.piggyvest.com" },
  { label: "Cowrywise", url: "https://my.cowrywise.com/login" },
];
const ngn = (v: string | null) => v === null ? "—" : new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", minimumFractionDigits: 2 }).format(Number(v));
const signed = (v: string | null) => v === null ? "—" : `${Number(v) >= 0 ? "+" : "−"}${ngn(String(Math.abs(Number(v))))}`;
export default function Calculator() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [config, setConfig] = useState<Config | null>(null); const [mode, setMode] = useState<"amount" | "shares">("amount"); const [amount, setAmount] = useState(""); const [shares, setShares] = useState(""); const [selling, setSelling] = useState(""); const [feePercent, setFeePercent] = useState(""); const [flatFee, setFlatFee] = useState(""); const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState(""); const [saveMessage, setSaveMessage] = useState(""); const [saveSucceeded, setSaveSucceeded] = useState(false); const [saveRequiresLogin, setSaveRequiresLogin] = useState(false); const [offerRefreshError, setOfferRefreshError] = useState(""); const [loading, setLoading] = useState(false); const [hasCalculated, setHasCalculated] = useState(false);
  useEffect(() => {
    let active = true;
    async function refreshOffer() {
      try {
        const response = await fetch("/api/ipo/dangote", { cache: "no-store" });
        if (!response.ok) throw new Error("Offer refresh failed");
        const nextConfig = await response.json() as Config;
        if (active) { setConfig(nextConfig); setOfferRefreshError(""); }
      } catch {
        if (active) setOfferRefreshError("Refresh unavailable; showing the last loaded snapshot.");
      }
    }
    void refreshOffer();
    const interval = window.setInterval(refreshOffer, 60_000);
    return () => { active = false; window.clearInterval(interval); };
  }, []);
  const payload = useCallback(() => ({ mode, investmentAmount: mode === "amount" ? amount : undefined, shares: mode === "shares" ? shares : undefined, expectedSellingPrice: selling || undefined, feePercent, flatFee }), [amount, feePercent, flatFee, mode, selling, shares]);
  async function calculate(e?: FormEvent) { e?.preventDefault(); setLoading(true); setError(""); const response = await fetch("/api/ipo/calculate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload()) }); const data = await response.json(); setLoading(false); if (!response.ok) return setError(data.error || "The Dangote IPO estimate could not be calculated. Check your entries and try again."); setHasCalculated(true); setResult(data.result); }
  useEffect(() => { if (!hasCalculated) return; const timeout = window.setTimeout(async () => { const response = await fetch("/api/ipo/calculate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload()) }); if (response.ok) { const data = await response.json(); setResult(data.result); setError(""); } }, 500); return () => window.clearTimeout(timeout); }, [config?.version, hasCalculated, payload]);
  async function save() { setSaveMessage(""); setSaveSucceeded(false); setSaveRequiresLogin(false); try { const response = await fetch("/api/ipo/history", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload()) }); const data = await response.json(); if (!response.ok) { setSaveMessage(data.error || "This Dangote IPO scenario could not be saved."); setSaveRequiresLogin(response.status === 401); return; } setSaveSucceeded(true); setSaveMessage("Saved to your account. You can view it in Saved IPO scenarios."); } catch { setSaveMessage("This Dangote IPO scenario could not be saved. Check your connection and try again."); } }
  const scenarioPrices = useMemo(() => [{ name: "Lower selling-price assumption", value: "" }, { name: "At the published offer price", value: config?.offerPriceNgn ?? "" }, { name: "Higher selling-price assumption", value: "" }], [config?.offerPriceNgn]);
  return <main className="calculator-page">
    <nav className={`calculator-nav${menuOpen ? " menu-open" : ""}`} aria-label="Main navigation"><a className="brand" href="/dangote-ipo-calculator" aria-label="Dangote IPO Calculator home"><Image unoptimized src="https://ipo.dangote.com/assets/logo-Btkv3LWu.png" alt="The IPO for the People" width={220} height={80} /><span className="brand-label">IPO Calculator</span></a><button className="nav-menu-toggle" type="button" aria-controls="calculator-nav-actions" aria-expanded={menuOpen} aria-label={menuOpen ? "Close navigation menu" : "Open navigation menu"} onClick={() => setMenuOpen((open) => !open)}><span /><span /><span /></button><div className="nav-actions" id="calculator-nav-actions"><a className="history-link primary" href="#investor-support" onClick={() => setMenuOpen(false)}>Support Chat</a><a className="history-link primary" href="/dangote-ipo-calculator/history" onClick={() => setMenuOpen(false)}>Saved IPO scenarios <span aria-hidden="true">→</span></a></div></nav>
    <section className="hero"><p className="eyebrow">DANGOTE REFINERY PUBLIC OFFER · VERIFIED TERMS</p><h1>Estimate your <em>Dangote IPO</em> investment.</h1><p>Enter the naira amount you plan to apply with, or a share quantity. The calculator uses the verified Dangote Refinery IPO offer price and share-lot rules shown below, then applies the fee and selling-price assumptions you enter to estimate cash required and a possible gain or loss. It does not submit an application or predict a market price.</p>{config && <div className="verified"><span>✓ Published offer price</span><strong>{ngn(config.offerPriceNgn)} / share</strong><span>Official sources reviewed {config.lastVerified}</span><time dateTime={config.snapshotRetrievedAt}>Snapshot loaded {new Intl.DateTimeFormat("en-NG", { hour: "2-digit", minute: "2-digit", second: "2-digit" }).format(new Date(config.snapshotRetrievedAt))} · refreshes every 60 seconds</time><span className="refresh-status" role="status">{offerRefreshError}</span></div>}</section>
    <section className="workspace" aria-label="Dangote IPO calculator"><form onSubmit={calculate} className="inputs card"><div className="section-head"><span>01 / Enter your application assumptions</span><small>Offer price and share-lot rules are verified facts; fee and sale-price fields are yours.</small></div><div className="switch" role="group" aria-label="Choose how to calculate your IPO application"><button type="button" className={mode === "amount" ? "active" : ""} onClick={() => setMode("amount")}>I have a naira budget</button><button type="button" className={mode === "shares" ? "active" : ""} onClick={() => setMode("shares")}>I have a share quantity</button></div>{mode === "amount" ? <Field label="Cash available for the application" prefix="₦" value={amount} change={setAmount} placeholder="Enter budget" hint="Budget for offer shares and the fee amounts entered below." /> : <Field label="Shares you plan to apply for" value={shares} change={setShares} placeholder="Enter share quantity" hint={`Must meet the ${config?.minimumShares ?? 10}-share minimum and use ${config?.quantityIncrement ?? 10}-share lots.`} />}
      <div className="readonly"><span>Verified offer price</span><b>{config ? ngn(config.offerPriceNgn) : "Loading offer terms…"}</b><small>Published offer term · not editable</small></div><Field label="Selling price per share" prefix="₦" value={selling} change={setSelling} placeholder="Enter selling price" hint="Your estimate only. No live market price is available here." /><div className="two"><Field label="Application fee (%)" value={feePercent} change={setFeePercent} placeholder="Enter fee percentage" hint="Enter the rate quoted by your provider. Leave blank to exclude a fee." /><Field label="Additional flat fee" prefix="₦" value={flatFee} change={setFlatFee} placeholder="Enter fees" hint="Enter your estimate of any fixed application charge." /></div><button className="primary" disabled={loading || !config}>{loading ? "Calculating your application…" : "Calculate shares and cost"}</button>{error && <p className="message" role="status">{error}</p>}</form>
      <section className="results card" aria-live="polite"><div className="section-head"><span>02 / Calculated application estimate</span><small>Recalculated by the server using the current offer snapshot</small></div>{!result ? <div className="empty"><b>Your Dangote IPO estimate will appear here.</b><p>Enter a budget or share quantity and select “Calculate shares and cost” to see the share count, fees, total cash, and any result based on your selling-price assumption.</p></div> : <><div className="headline"><span>Estimated gain or loss at your selling price</span><strong className={Number(result.potentialGainLoss) >= 0 ? "positive" : "negative"}>{signed(result.potentialGainLoss)}</strong><b>{result.percentageReturn === null ? "Enter your selling-price assumption to estimate a return" : `${result.percentageReturn}% estimated return at your assumed price`}</b></div><div className="grid-results"><Metric label="Eligible shares estimated" value={Number(result.shares).toLocaleString("en-NG")} /><Metric label="Offer-share cost" value={ngn(result.investmentCost)} /><Metric label="Fees you entered" value={ngn(result.fees)} /><Metric label="Total application cash" value={ngn(result.totalCashRequired)} /><Metric label="Value at your assumed price" value={ngn(result.estimatedPositionValue)} /><Metric label="Break-even estimate per share" value={ngn(result.breakEvenPrice)} /></div>{result.remainingCash !== null && <p className="remaining">Budget remaining after modeled cost and fees: <b>{ngn(result.remainingCash)}</b></p>}<PositionChart investmentCost={result.investmentCost} positionValue={result.estimatedPositionValue} shares={result.shares} /><div className="result-actions"><button type="button" className="primary save-estimate" onClick={save}>Save this IPO estimate</button><a className="link-btn" href="#investor-support">Ask the Dangote IPO support chat</a></div>{saveMessage && <p className={`message save-message${saveSucceeded ? " success" : ""}`} role="status">{saveMessage}{saveRequiresLogin && <> <a href="/login?callbackUrl=%2Fdangote-ipo-calculator">Sign in to save this estimate.</a></>}</p>}<div className="investment-platforms"><h3>Ready to invest?</h3><p>Choose an approved channel that works for you. These links are listed on the official Dangote IPO site; they are not recommendations.</p><div className="reference-list">{investmentPlatforms.map(platform => <a key={platform.label} href={platform.url} target="_blank" rel="noreferrer"><span>{platform.label}</span><span aria-hidden="true">↗</span></a>)}</div><a className="all-platforms-link" href="https://ipo.dangote.com/subscribe" target="_blank" rel="noreferrer">View all approved subscription channels on the official Dangote IPO site ↗</a></div></>}</section></section>
    <section className="scenarios card"><div className="section-head"><span>03 / Compare selling-price assumptions</span><small>Change the prices to compare outcomes; none is a forecast.</small></div><div className="scenario-grid">{scenarioPrices.map((s, i) => <Scenario key={s.name} label={s.name} initial={s.value} shares={result?.shares} total={result?.totalCashRequired} />)}</div><p>Each comparison uses the share quantity and total cash from your latest estimate. The middle field starts at the published offer price; all three fields are editable. Selling fees are excluded because no official selling-fee schedule is available in the offer snapshot.</p></section>
    <SupportChat calculatorInput={result ? payload() : undefined} />
    <Info config={config} />
    <Footer sources={config?.sources ?? []} />
  </main>;
}
function Field({ label, prefix, value, change, hint, placeholder }: { label: string; prefix?: string; value: string; change: (v: string) => void; hint: string; placeholder?: string }) { return <label className="field"><span>{label}</span><div>{prefix && <i>{prefix}</i>}<input inputMode="decimal" value={value} onChange={e => change(e.target.value)} aria-label={label} placeholder={placeholder} /></div><small>{hint}</small></label>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><b>{value}</b></div>; }
function Scenario({ label, initial, shares, total }: { label: string; initial: string; shares?: string; total?: string }) { const [price, setPrice] = useState(initial); useEffect(() => setPrice(initial), [initial]); const val = Number(shares || 0) * Number(price || 0); const gain = total && price ? val - Number(total) : null; const base = Number(total || 0); return <div className="scenario"><label>{label}<input aria-label={`${label} selling-price assumption per share`} inputMode="decimal" value={price} onChange={e => setPrice(e.target.value)} /></label><span>Estimated share value</span><b>{price && shares ? ngn(String(val)) : "—"}</b><small>{gain === null ? "Enter a price to compare" : `${signed(String(gain))} · ${base ? ((gain / base) * 100).toFixed(2) : "0.00"}% estimated`}</small></div>; }
function Info({ config }: { config: Config | null }) {
  return <section className="content">
    <article><p className="eyebrow">VERIFIED DANGOTE IPO TERMS</p><h2 id="offer-information">Published offer details used in this estimate.</h2><p><b>Offer facts:</b> {config ? `${config.issuer}; ${ngn(config.offerPriceNgn)} per share; minimum ${config.minimumShares} shares, in lots of ${config.quantityIncrement}; offer dates ${config.opensOn} to ${config.closesOn}.` : "Loading the published Dangote Refinery IPO terms."}</p><p><b>Not available in this calculator:</b> an official application-fee schedule, declared dividend information, allotment outcome, or live market price. Enter your own fee and selling-price assumptions where the calculator asks for them.</p>{config && <p className="sources">Official and regulatory references: {config.sources.map((s, i) => <a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.label}{i < config.sources.length - 1 ? " · " : ""}</a>)}</p>}</article>
    <article><p className="eyebrow">CALCULATION METHOD</p><h2>How your share count and estimated outcome are calculated.</h2><p>With a cash budget, the calculator finds the largest eligible share lot whose offer cost plus the fee assumptions you entered fits within that budget. With a share quantity, it checks the published minimum and lot increment. Offer cost is shares multiplied by the verified offer price; modeled fees are the entered percentage of offer cost plus your flat fee. Total application cash is offer cost plus those modeled fees.</p><p>If you enter a selling price, estimated share value is shares multiplied by that price. Estimated gain or loss is that value minus total application cash. Break-even per share is total application cash divided by shares, rounded up to the nearest kobo. Selling fees and taxes are not included.</p></article>
    <article><p className="eyebrow">RISKS AND LIMITS</p><h2>What this estimate cannot tell you.</h2><p>This calculator does not submit an IPO application, confirm eligibility, reserve shares, or predict allotment. An application may receive fewer shares than requested. The selling price is your assumption, not a quoted or forecast market price; you may be unable to sell when or at the price you expect.</p><p>Share values can fall and you could lose some or all of the amount invested. No official application or selling-fee schedule, dividend, tax, or future market price is included unless you enter a fee assumption yourself. Read the current prospectus and seek advice from an authorised professional if you need personal investment guidance.</p></article>
    <article className="issuer-media"><Image className="issuer-refinery" unoptimized src="https://ipo.dangote.com/assets/hero-home-aerial-BFiTR4FN.jpg" alt="Aerial view of the Dangote refinery" width={1280} height={800} /><div><Image className="issuer-logo" unoptimized src="https://ipo.dangote.com/assets/logo-Btkv3LWu.png" alt="The IPO for the People" width={220} height={150} /><p className="eyebrow">ISSUER INFORMATION</p><h2>Read the issuer&apos;s offer guidance.</h2><p>The issuer explains what a share represents, how the public offer works, and where to find official subscription instructions. Read the approved prospectus before applying; this calculator is not an application channel.</p><p className="media-links"><a href="https://ipo.dangote.com/about" target="_blank" rel="noreferrer">Dangote IPO guide to shares and the offer</a><a href="https://www.instagram.com/dangote.ipo/" target="_blank" rel="noreferrer">Dangote IPO official Instagram notices</a><a href="https://www.tiktok.com/@dangoteipo" target="_blank" rel="noreferrer">Dangote IPO official TikTok notices</a></p></div></article>
    <section className="reference-links" aria-labelledby="reference-title"><p className="eyebrow">OFFER DOCUMENTS AND REGULATORY NOTICES</p><h2 id="reference-title">Check the IPO terms with the issuer, SEC Nigeria, and NGX.</h2><p>Use these references to confirm the prospectus, offer price and dates, and any later notices. The snapshot above is only as current as its published verification date.</p><div className="reference-list">{config?.sources.map(source => <a key={source.url} href={source.url} target="_blank" rel="noreferrer"><span>{source.label}</span><span aria-hidden="true">↗</span></a>)}<a href="https://refinery.dangote.com/" target="_blank" rel="noreferrer"><span>Dangote Refinery company information</span><span aria-hidden="true">↗</span></a></div></section>
    <Faq />
  </section>;
}

function Footer({ sources }: { sources: Config["sources"] }) {
  const profiles = [
    { label: "GitHub", href: "https://github.com/vick-tory1/" },
    { label: "LinkedIn", href: "https://www.linkedin.com/in/adams-ekpe" },
    { label: "X / Twitter", href: "https://x.com/adamsking321" },
    { label: "Facebook", href: "https://www.facebook.com/share/19g2CfaFTu/?mibextid=wwXIfr" },
    { label: "Instagram", href: "https://www.instagram.com/ekpe.adams/" },
    { label: "TikTok", href: "https://www.tiktok.com/@yhwh.._s_..chosen?_r=1&_t=ZN-9ACUwYvMtfi" },
  ];

  return <footer className="site-footer">
    <div className="site-footer-inner">
      <section className="footer-owner"><Image unoptimized src="https://ipo.dangote.com/assets/logo-Btkv3LWu.png" alt="The IPO for the People" width={220} height={80} /><h2>Dangote Refinery IPO Calculator</h2><p>Built by <strong>Adams Ekpe</strong>, aka <strong>YHWH&apos;s Chosen</strong>.</p><p>This tool estimates shares and application cash from published offer terms and the assumptions entered by each investor. It does not accept IPO applications.</p></section>
      <section className="footer-navigation"><h2>Calculator</h2><a href="/dangote-ipo-calculator">Estimate shares and cash</a><a href="/dangote-ipo-calculator/history">Saved IPO estimates</a><a href="#offer-information">Published offer terms</a><a href="#investor-support">Ask the IPO support chat</a></section>
      <section className="footer-references"><h2>Official references</h2>{sources.map(source => <a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.label}<span aria-hidden="true">↗</span></a>)}<a href="https://refinery.dangote.com/" target="_blank" rel="noreferrer">Dangote Refinery company site<span aria-hidden="true">↗</span></a></section>
      <section className="footer-social" aria-label="Adams Ekpe social profiles"><h2>Connect with Adams</h2>{profiles.map(profile => <a key={profile.label} href={profile.href} target="_blank" rel="noreferrer">{profile.label}<span aria-hidden="true">↗</span></a>)}</section>
    </div>
    <p className="footer-bottom">© {new Date().getFullYear()} Adams Ekpe · Dangote Refinery IPO Calculator</p>
  </footer>;
}
